[package]
name = "lexwisp-platform-windows"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
async-channel.workspace = true
lexwisp-core.workspace = true
thiserror.workspace = true
tokio.workspace = true
windows-sys.workspace = true

[lints]
workspace = true
