[package]
name = "lexwisp-plugins-builtin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
async-channel.workspace = true
gpui-kit.workspace = true
lexwisp-core.workspace = true
lexwisp-ui.workspace = true

[lints]
workspace = true

[dev-dependencies]
futures-lite.workspace = true
