[package]
name = "lexwisp-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "LexWisp"
path = "src/main.rs"

[dependencies]
async-channel.workspace = true
gpui-kit.workspace = true
lexwisp-core.workspace = true
lexwisp-host.workspace = true
lexwisp-platform-windows.workspace = true
lexwisp-plugins-builtin.workspace = true
lexwisp-plugins-script.workspace = true
lexwisp-storage.workspace = true
lexwisp-ui.workspace = true
raw-window-handle.workspace = true

[dev-dependencies]
rquickjs.workspace = true

[lints]
workspace = true
